# Generated by Django 2.2.6 on 2019-11-02 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20191102_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_at'], 'verbose_name': 'servicio', 'verbose_name_plural': 'servicios'},
        ),
    ]
